/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;

import javax.swing.JOptionPane;
import org.bson.Document;

/**
 *
 * @author Alfredo Perez
 */
public class DlgAlumnoLista extends javax.swing.JDialog 
{

    private Document alumno;
    private int accion;
    
    /**
     * Modificar alumno
     * Creates new form DlgAlumnoLista
     * @param parent
     * @param modal
     * @param alumnoSeleccionado
     * @param accion 
     */
    public DlgAlumnoLista(java.awt.Frame parent, boolean modal, Document alumnoSeleccionado, int accion) 
    {
        super(parent, modal);
        this.initComponents();
        this.alumno = alumnoSeleccionado;
        this.accion = accion;
        if(accion == ConstantesGUI.MODIFICAR)
        {
            this.setTitle("Modificar Alumno");
            this.setAtributosAlumno();
        }
        else if(accion == ConstantesGUI.AGREGAR)
        {
           this.setTitle("Agregar Alumno");
           this.etiquetaTitulo.setText("Agregar alumno");
           this.botonAceptar.setText("Agregar"); 
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        etiquetaTitulo = new javax.swing.JLabel();
        etiquetaNombreCompleto = new javax.swing.JLabel();
        etiquetaEstadoAsistencia = new javax.swing.JLabel();
        etiquetaHoraEntrada = new javax.swing.JLabel();
        etiquetaMinutosTotales = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        comboEstadoAsistencia = new javax.swing.JComboBox<>();
        txtHora = new javax.swing.JFormattedTextField();
        txtMinutosTotales = new javax.swing.JSpinner();
        panelBotonAceptar = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        panelBotonSalir = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(240, 202, 171));

        etiquetaTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        etiquetaTitulo.setText("Modificar alumno");

        etiquetaNombreCompleto.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        etiquetaNombreCompleto.setText("Nombre completo: ");

        etiquetaEstadoAsistencia.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        etiquetaEstadoAsistencia.setText("Estado asistencia: ");

        etiquetaHoraEntrada.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        etiquetaHoraEntrada.setText("Hora entrada: ");

        etiquetaMinutosTotales.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        etiquetaMinutosTotales.setText("Minutos totales: ");

        txtNombreCompleto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNombreCompleto.setPreferredSize(new java.awt.Dimension(260, 25));

        comboEstadoAsistencia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboEstadoAsistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione estado de asistencia", "Asistio", "No Asistio" }));
        comboEstadoAsistencia.setPreferredSize(new java.awt.Dimension(260, 29));
        comboEstadoAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadoAsistenciaActionPerformed(evt);
            }
        });

        try {
            txtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHora.setText("");

        txtMinutosTotales.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtMinutosTotales.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        txtMinutosTotales.setPreferredSize(new java.awt.Dimension(68, 25));

        panelBotonAceptar.setBackground(new java.awt.Color(51, 255, 51));
        panelBotonAceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotonAceptar.setPreferredSize(new java.awt.Dimension(100, 30));

        botonAceptar.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        botonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        botonAceptar.setText("Actualizar");
        botonAceptar.setContentAreaFilled(false);
        botonAceptar.setPreferredSize(new java.awt.Dimension(100, 30));
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonAceptarLayout = new javax.swing.GroupLayout(panelBotonAceptar);
        panelBotonAceptar.setLayout(panelBotonAceptarLayout);
        panelBotonAceptarLayout.setHorizontalGroup(
            panelBotonAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonAceptarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBotonAceptarLayout.setVerticalGroup(
            panelBotonAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonAceptarLayout.createSequentialGroup()
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelBotonSalir.setBackground(new java.awt.Color(0, 0, 0));
        panelBotonSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotonSalir.setPreferredSize(new java.awt.Dimension(100, 30));

        botonSalir.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Cancelar");
        botonSalir.setContentAreaFilled(false);
        botonSalir.setPreferredSize(new java.awt.Dimension(100, 30));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonSalirLayout = new javax.swing.GroupLayout(panelBotonSalir);
        panelBotonSalir.setLayout(panelBotonSalirLayout);
        panelBotonSalirLayout.setHorizontalGroup(
            panelBotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBotonSalirLayout.setVerticalGroup(
            panelBotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaMinutosTotales)
                    .addComponent(etiquetaHoraEntrada)
                    .addComponent(etiquetaEstadoAsistencia)
                    .addComponent(etiquetaNombreCompleto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtMinutosTotales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHora, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNombreCompleto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboEstadoAsistencia, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelFondoLayout.createSequentialGroup()
                            .addComponent(panelBotonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelBotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetaTitulo)
                .addGap(100, 100, 100))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(etiquetaTitulo)
                .addGap(50, 50, 50)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombreCompleto)
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaEstadoAsistencia)
                    .addComponent(comboEstadoAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaHoraEntrada)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaMinutosTotales)
                    .addComponent(txtMinutosTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(panelBotonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(90, Short.MAX_VALUE))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(panelBotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.alumno = null;
        dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
     if(validarCampos())
     {
        alumno.put("nombre", txtNombreCompleto.getText());
        alumno.put("estadoAsistencia", comboEstadoAsistencia.getSelectedItem().toString());
        validarAsistencia();
     }
     
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void validarAsistencia()
    {
        if(comboEstadoAsistencia.getSelectedIndex() ==1)
        {
            String hora;
            hora = validarHora(txtHora.getText());
            if(hora!=null)
            {
                alumno.put("horaEntrada", txtHora.getText());
                alumno.put("minutosTotales", txtMinutosTotales.getValue().toString());
                dispose();
            }else{JOptionPane.showMessageDialog(this, "Error! \n El campo hora es incorrecto", "Mensaje Error", JOptionPane.ERROR_MESSAGE);}
        }
        else if(comboEstadoAsistencia.getSelectedIndex() ==2)
        {
            alumno.put("horaEntrada", "");
            alumno.put("minutosTotales", "");
            dispose();
        }
    }
    
    private boolean validarCampos()
    {
        if(txtNombreCompleto.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Error \n El campo nombre no puede estar vacio!", "Mensaje Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(comboEstadoAsistencia.getSelectedIndex() == 0)
        {
            JOptionPane.showMessageDialog(this, "Error \n No se selecciono el estado de asistencia!", "Mensaje Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    
    private String validarHora(String cadenaHora)
    {
        String[] hora;
        hora = cadenaHora.split(":");
        
        if((hora[0].equals("  ")) || (hora[1].equals("  ")))
        {
            txtHora.setText("");
            return null;
        }
        
        if(((Integer.valueOf(hora[0])>=0) && (Integer.valueOf(hora[0])<25))&&
           ((Integer.valueOf(hora[1])>=0) && (Integer.valueOf(hora[1])<61)))
        {
            return hora[0]+":"+hora[1];
        }
        txtHora.setText("");
        return null;
    }
    
    
    
    private void comboEstadoAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoAsistenciaActionPerformed
           if(comboEstadoAsistencia.getSelectedIndex()==1)
           {
               if(accion == 1)
               {
                   this.txtHora.setText(alumno.getString("horaEntrada"));
                   if(!alumno.getString("minutosTotales").equals("")){this.txtMinutosTotales.setValue(Integer.valueOf(alumno.getString("minutosTotales")));}
               }
               txtHora.setEnabled(true);
               txtMinutosTotales.setEnabled(true);
           }
           else if(comboEstadoAsistencia.getSelectedIndex()==2)
           {
               txtHora.setText("");
               txtMinutosTotales.setValue(0);
               txtHora.setEnabled(false);
               txtMinutosTotales.setEnabled(false);
           }
    }//GEN-LAST:event_comboEstadoAsistenciaActionPerformed

    private void setAtributosAlumno()
    {
        this.txtNombreCompleto.setText(alumno.getString("nombre"));
        if(alumno.getString("estadoAsistencia").equals("Asistio")){comboEstadoAsistencia.setSelectedIndex(1);}
        else if(alumno.getString("estadoAsistencia").equals("No Asistio")){comboEstadoAsistencia.setSelectedIndex(2);}
        this.txtHora.setText(alumno.getString("horaEntrada"));
        if(!alumno.getString("minutosTotales").equals("")){this.txtMinutosTotales.setValue(Integer.valueOf(alumno.getString("minutosTotales")));}
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> comboEstadoAsistencia;
    private javax.swing.JLabel etiquetaEstadoAsistencia;
    private javax.swing.JLabel etiquetaHoraEntrada;
    private javax.swing.JLabel etiquetaMinutosTotales;
    private javax.swing.JLabel etiquetaNombreCompleto;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel panelBotonAceptar;
    private javax.swing.JPanel panelBotonSalir;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JFormattedTextField txtHora;
    private javax.swing.JSpinner txtMinutosTotales;
    private javax.swing.JTextField txtNombreCompleto;
    // End of variables declaration//GEN-END:variables
}
