/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;

import interpreter.Interpreter;
import objetosNegocio.*;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.bson.Document;
import repository.AsistenciaCursosRepository;
import repository.CursosRepository;

/**
 *
 * @author Alfredo Perez
 */
public class DlgAgregarAsistencia extends javax.swing.JDialog 
{
    private Interpreter interpreteArchivo = new Interpreter();;
    private List<String[]> listaContenido;
    private MiRender mirender = new MiRender();
    private AsistenciaCursosRepository asistenciaCursosRepository;
    private CursosRepository cursosRepo;
    
    /**
     * Creates new form DlgAgregarAsistencia
     * @param parent
     * @param modal
     * @param asistenciaCursosRepository
     * @param cursosRepo
     */
    public DlgAgregarAsistencia(java.awt.Frame parent, boolean modal, AsistenciaCursosRepository asistenciaCursosRepository, CursosRepository cursosRepo) 
    {
        super(parent, modal);
        this.initComponents();
        this.asistenciaCursosRepository = asistenciaCursosRepository;
        this.cursosRepo = cursosRepo;
        this.llenarComboBoxCursos();
        this.listaContenido = new ArrayList<>();
        this.actualizarTablaLista();
        this.tablaLista.setDefaultRenderer(tablaLista.getColumnClass(1) ,mirender);
        this.setTitle("Menu agregar asistencia");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        txtSelectorArchivo = new javax.swing.JTextField();
        etiquetaSeleccionarArchivo = new javax.swing.JLabel();
        botonBuscarArchivo = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        botonCanelar = new javax.swing.JButton();
        etiquetaTitulo = new javax.swing.JLabel();
        scrollPanelTablaLista = new javax.swing.JScrollPane();
        tablaLista = new javax.swing.JTable();
        etiquetaSeleccionarCurso = new javax.swing.JLabel();
        comboBoxCursos = new javax.swing.JComboBox<>();
        etiquetaFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        panelFondo.setBackground(new java.awt.Color(240, 202, 171));

        txtSelectorArchivo.setEditable(false);
        txtSelectorArchivo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtSelectorArchivo.setRequestFocusEnabled(false);
        txtSelectorArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSelectorArchivoMousePressed(evt);
            }
        });

        etiquetaSeleccionarArchivo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        etiquetaSeleccionarArchivo.setText("Seleccionar archivo: ");

        botonBuscarArchivo.setText("....");
        botonBuscarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarArchivoActionPerformed(evt);
            }
        });

        botonAceptar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCanelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botonCanelar.setText("Cancelar");
        botonCanelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCanelarActionPerformed(evt);
            }
        });

        etiquetaTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        etiquetaTitulo.setText("Agregar asistencia");

        tablaLista.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tablaLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrollPanelTablaLista.setViewportView(tablaLista);

        etiquetaSeleccionarCurso.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        etiquetaSeleccionarCurso.setText("Seleccionar curso: ");

        comboBoxCursos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        comboBoxCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar curso" }));

        etiquetaFecha.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        etiquetaFecha.setText("Fecha: ");

        txtFecha.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(etiquetaTitulo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(scrollPanelTablaLista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFondoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonAceptar)
                                .addGap(23, 23, 23)
                                .addComponent(botonCanelar)))
                        .addGap(35, 35, 35))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etiquetaSeleccionarArchivo)
                                    .addComponent(etiquetaSeleccionarCurso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSelectorArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                                    .addComponent(comboBoxCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonBuscarArchivo))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(etiquetaFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(etiquetaTitulo)
                .addGap(32, 32, 32)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaSeleccionarArchivo)
                    .addComponent(txtSelectorArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaSeleccionarCurso)
                    .addComponent(comboBoxCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(etiquetaFecha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanelTablaLista, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCanelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarArchivoActionPerformed
       File archivo = seleccionarArchivo();
        if(archivo!=null)
        {
            if(comprobarArchivo(archivo.getName()))
            {
                listaContenido = interpreteArchivo.importarArchivo(archivo);
                if(listaContenido != null)
                {
                    txtSelectorArchivo.setText(archivo.getPath());
                    txtFecha.setText(convertirFecha(listaContenido.get(0)[0]));
                    actualizarTablaLista();
                }else{JOptionPane.showMessageDialog(this, "Error! \n No se pudo importar el archivo.", "Mensaje Error", JOptionPane.ERROR_MESSAGE);}
            }else{JOptionPane.showMessageDialog(this, "Error! \n El tipo de archivo es incorrecto. \n Favor de solo ingresar archivos con la extencion \".CSV\" ", "Mensaje Error", JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_botonBuscarArchivoActionPerformed

    private void botonCanelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCanelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCanelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if(validarCampos())
        {   
             Document doc = new Document();
             doc.append("curso", extraerCurso());
             doc.append("fecha", convertirFecha(listaContenido.get(0)[0]));
             doc.append("listaAsistencia", obtenerListaContendioJSON());
             if(comprobarSiElRegistroExiste(extraerCurso(), convertirFecha(listaContenido.get(0)[0])))
             {
                if(asistenciaCursosRepository.agregarDoumento(doc))
                {
                    JOptionPane.showMessageDialog(this, "La asistencia se agrego con exito!", "Mesaje Aviso", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }else{JOptionPane.showMessageDialog(this, "Error! \n No se pudo agregar la asistencia!", "Mensaje Error", JOptionPane.ERROR_MESSAGE);}
             }else{JOptionPane.showMessageDialog(this, "Error! \n Ya hay un registro en la fecha:"+convertirFecha(listaContenido.get(0)[0])+"\n para el curso seleccionado!", "Mensaje Error", JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private boolean validarCampos()
    {
       if(listaContenido.isEmpty())
       {
           JOptionPane.showMessageDialog(this, "Error! \n No se ha abierto ningun documento con contenido", "Mensaje Error", JOptionPane.ERROR_MESSAGE);
           return false;
       }
        else if(!comprovarSelectorCurso())
       {
           JOptionPane.showMessageDialog(this, "Error! \n No se ha seleccionado ningun curso", "Mensaje Error", JOptionPane.ERROR_MESSAGE);
           return false;
       }
       return true;    
    }
    
    private void txtSelectorArchivoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSelectorArchivoMousePressed
        File archivo = seleccionarArchivo();
        if(archivo!=null)
        {
            if(comprobarArchivo(archivo.getName()))
            {
                listaContenido = interpreteArchivo.importarArchivo(archivo);
                if(listaContenido != null)
                {
                    txtSelectorArchivo.setText(archivo.getPath());
                    txtFecha.setText(convertirFecha(listaContenido.get(0)[0]));
                    actualizarTablaLista();
                }else{JOptionPane.showMessageDialog(this, "Error! \n No se pudo importar el archivo.", "Mensaje Error", JOptionPane.ERROR_MESSAGE);}
            }else{JOptionPane.showMessageDialog(this, "Error! \n El tipo de archivo es incorrecto. \n Favor de solo ingresar archivos con la extencion \".CSV\" ", "Mensaje Error", JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_txtSelectorArchivoMousePressed

    private boolean comprobarSiElRegistroExiste(Document documento, String fecha)
    {
        return asistenciaCursosRepository.buscarListaAsistencias(documento, fecha) == null;
    }
    
    private Document extraerCurso()
    {
        String[] curso;
        Document documentoCurso = new Document();
        curso = comboBoxCursos.getSelectedItem().toString().split(",");
        documentoCurso.append("nombre", curso[0].substring(curso[0].indexOf(":")+2, curso[0].length()));
        documentoCurso.append("periodo", curso[1].substring(curso[1].indexOf(":")+2, curso[1].length()));
        documentoCurso.append("dias", curso[2].substring(curso[2].indexOf(":")+2, curso[2].length()));
        documentoCurso.append("hora", curso[3].substring(curso[3].indexOf(":")+2, curso[3].length()));
        return documentoCurso;
    }
    
    private String convertirFecha(String fecha)
    {
        String[] arregloFecha;
        //Dia[2]/Mes[1]/Año[0]
        arregloFecha = fecha.split("-");
        return arregloFecha[2]+"/"+arregloFecha[1]+"/"+arregloFecha[0];
    }
    
    private List<Document> obtenerListaContendioJSON()
    {
        List<Document> listaContenidoJSON = new ArrayList<>();
        for(int cont =1;cont < listaContenido.size() ; cont++)
        {
           Document documento = new Document();
           documento.append("nombre", listaContenido.get(cont)[0]);
           documento.append("estadoAsistencia", listaContenido.get(cont)[1]);
           documento.append("horaEntrada", listaContenido.get(cont)[2]);
           documento.append("minutosTotales", listaContenido.get(cont)[3]);
           listaContenidoJSON.add(documento);
        }
        return listaContenidoJSON;
    }
    
    private boolean comprovarSelectorCurso()
    {
        return !comboBoxCursos.getSelectedItem().equals("Seleccionar curso");
    }
    
    
    private boolean comprobarArchivo(String nombreArchivo)
    {
        return nombreArchivo.substring(nombreArchivo.indexOf("."), nombreArchivo.length()).equals(".csv");
    }
    
    private Object[][] comprobarLista()
    {
        if(listaContenido.isEmpty()) {return new Object[0][0];}
        else{return interpreteArchivo.getConteridoTabla(listaContenido);}
    }
    
    private void actualizarTablaLista()
    {
       tablaLista.setModel(new javax.swing.table.DefaultTableModel(
            comprobarLista(),
            new String []{"Num.","Nombre Completo", "Estado asistencia", "Hora entrada", "Minutos totales"}
        ) {
            Class[] types = new Class [] {
                java.lang.String.class,java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
                
            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            
            boolean[] canEdit = new boolean [] {false, false, false, false, false};

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        }); 
            tablaLista.getColumnModel().getColumn(0).setResizable(false);
            tablaLista.getColumnModel().getColumn(1).setResizable(false);
            tablaLista.getColumnModel().getColumn(2).setResizable(false);
            tablaLista.getColumnModel().getColumn(3).setResizable(false);
            tablaLista.getColumnModel().getColumn(4).setResizable(false);
            tablaLista.getColumnModel().getColumn(0).setPreferredWidth(1);
            tablaLista.getColumnModel().getColumn(1).setPreferredWidth(300);
    }
    
    
    private File seleccionarArchivo()
    {
        JFileChooser selectorArchivos = new JFileChooser();
        
        selectorArchivos.setFileFilter(new FileNameExtensionFilter(".csv", "csv"));
        
        int opcion = selectorArchivos.showOpenDialog(this);
        
        if(opcion ==JFileChooser.APPROVE_OPTION)
        {
            File archivo = selectorArchivos.getSelectedFile();
            return archivo;
        }else{return null;}
    }
    
    private void llenarComboBoxCursos()
    {
       List<Document> listaCursos = cursosRepo.buscarRegistrosEnLaColeccion();
       for(int cont=0 ;cont < listaCursos.size() ;cont++)
       {
           comboBoxCursos.addItem("Nombre: "+listaCursos.get(cont).getString("nombre")+
                                ", Periodo: "+listaCursos.get(cont).getString("periodo")+
                                ", Dias: "+listaCursos.get(cont).getString("dias")+
                                ", Hora: "+listaCursos.get(cont).getString("hora"));
       }
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonBuscarArchivo;
    private javax.swing.JButton botonCanelar;
    private javax.swing.JComboBox<String> comboBoxCursos;
    private javax.swing.JLabel etiquetaFecha;
    private javax.swing.JLabel etiquetaSeleccionarArchivo;
    private javax.swing.JLabel etiquetaSeleccionarCurso;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JScrollPane scrollPanelTablaLista;
    private javax.swing.JTable tablaLista;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JTextField txtSelectorArchivo;
    // End of variables declaration//GEN-END:variables

    
   
}
