/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;

import interpreter.Interpreter;
import objetosNegocio.*;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.bson.Document;
import repository.AsistenciaCursosRepository;
import repository.CursosRepository;

/**
 *
 * @author Alfredo Perez
 */
public class DlgAgregarAsistencia extends javax.swing.JDialog 
{
    private Interpreter interpreteArchivo;
    private List<String[]> listaContenido;
    private java.awt.Frame framePrincipal;
    private MiRender mirender = new MiRender();
    private AsistenciaCursosRepository asistenciaCursosRepository;
    private CursosRepository cursosRepo;
    
    /**
     * Creates new form DlgAgregarAsistencia
     * @param parent
     * @param modal
     * @param asistenciaCursosRepository
     * @param cursosRepo
     */
    public DlgAgregarAsistencia(java.awt.Frame parent, boolean modal, AsistenciaCursosRepository asistenciaCursosRepository, CursosRepository cursosRepo) 
    {
        super(parent, modal);
        this.initComponents();
        this.asistenciaCursosRepository = asistenciaCursosRepository;
        this.cursosRepo = cursosRepo;
        this.llenarComboBoxCursos();
        this.listaContenido = new ArrayList<>();
        this.actualizarTablaLista();
        this.framePrincipal = parent;
        this.tablaLista.setDefaultRenderer(tablaLista.getColumnClass(1) ,mirender);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        txtSelectorArchivo = new javax.swing.JTextField();
        etiquetaSeleccionarArchivo = new javax.swing.JLabel();
        botonBuscarArchivo = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        botonCanelar = new javax.swing.JButton();
        etiquetaTitulo = new javax.swing.JLabel();
        scrollPanelTablaLista = new javax.swing.JScrollPane();
        tablaLista = new javax.swing.JTable();
        etiquetaSeleccionarCurso = new javax.swing.JLabel();
        comboBoxCursos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        panelFondo.setBackground(new java.awt.Color(240, 202, 171));

        txtSelectorArchivo.setEditable(false);
        txtSelectorArchivo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtSelectorArchivo.setRequestFocusEnabled(false);
        txtSelectorArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSelectorArchivoActionPerformed(evt);
            }
        });

        etiquetaSeleccionarArchivo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        etiquetaSeleccionarArchivo.setText("Seleccionar archivo: ");

        botonBuscarArchivo.setText("....");
        botonBuscarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarArchivoActionPerformed(evt);
            }
        });

        botonAceptar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCanelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botonCanelar.setText("Cancelar");
        botonCanelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCanelarActionPerformed(evt);
            }
        });

        etiquetaTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        etiquetaTitulo.setText("Agregar Asistencia");

        tablaLista.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tablaLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrollPanelTablaLista.setViewportView(tablaLista);

        etiquetaSeleccionarCurso.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        etiquetaSeleccionarCurso.setText("Seleccionar curso: ");

        comboBoxCursos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        comboBoxCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar curso" }));

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(etiquetaTitulo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(scrollPanelTablaLista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFondoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonAceptar)
                                .addGap(23, 23, 23)
                                .addComponent(botonCanelar)))
                        .addGap(35, 35, 35))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiquetaSeleccionarCurso)
                            .addComponent(etiquetaSeleccionarArchivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSelectorArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                            .addComponent(comboBoxCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscarArchivo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(etiquetaTitulo)
                .addGap(32, 32, 32)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaSeleccionarArchivo)
                    .addComponent(txtSelectorArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaSeleccionarCurso)
                    .addComponent(comboBoxCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollPanelTablaLista, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCanelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarArchivoActionPerformed
        interpreteArchivo = new Interpreter();
        File archivo = seleccionarArchivo();
        if(archivo!=null)
        {
            if(comprobarArchivo(archivo.getName()))
            {
                listaContenido = interpreteArchivo.importarArchivo(archivo);
                if(listaContenido != null)
                {
                    txtSelectorArchivo.setText(archivo.getPath());
                    actualizarTablaLista();
                }
                else{JOptionPane.showMessageDialog(this, "Error! \n No se pudo importar el archivo.", "Mensaje Error", JOptionPane.ERROR_MESSAGE);}
            }
            else{JOptionPane.showMessageDialog(this, "Error! \n El tipo de archivo es incorrecto. \n Favor de solo ingresar archivos con la extencion \".CSV\" ", "Mensaje Error", JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_botonBuscarArchivoActionPerformed

    private void botonCanelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCanelarActionPerformed
        dispose();
        framePrincipal.setVisible(true);
    }//GEN-LAST:event_botonCanelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
      if(!listaContenido.isEmpty())
      {
          if(comprovarSelectorCurso())
          {
              Document doc = new Document();
              doc.append("nombreCurso", extraerNombreComboBoxSelectedItem());
              doc.append("dia", listaContenido.get(0)[0]);
              doc.append("listaAsistencia", obtenerListaContendioJSON());
              if(asistenciaCursosRepository.agregarDoumento(doc))
              {
                  JOptionPane.showMessageDialog(this, "La asistencia se agrego con exito!", "Mesaje Aviso", JOptionPane.INFORMATION_MESSAGE);
                  dispose();
                  framePrincipal.setVisible(true);
              }
              else{JOptionPane.showMessageDialog(this, "Error! \n No se pudo agregar la asistencia!", "Mensaje Error", JOptionPane.ERROR_MESSAGE);}
          }
          else{JOptionPane.showMessageDialog(this, "Error! \n No se ha seleccionado ningun curso", "Mensaje Error", JOptionPane.ERROR_MESSAGE);}
      }
      else{JOptionPane.showMessageDialog(this, "Error! \n No se ha abierto ningun documento con contenido", "Mensaje Error", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_botonAceptarActionPerformed

    private List<Document> obtenerListaContendioJSON()
    {
        List<Document> listaContenidoJSON = new ArrayList<>();
        for(int cont =1;cont < listaContenido.size() ; cont++)
        {
           Document documento = new Document();
           documento.append("nombre", listaContenido.get(cont)[0]);
           documento.append("EstadoAsistencia", listaContenido.get(cont)[1]);
           documento.append("HoraEntrada", listaContenido.get(cont)[2]);
           documento.append("MinutosTotales", listaContenido.get(cont)[3]);
           listaContenidoJSON.add(documento);
        }
        return listaContenidoJSON;
    }
    
    private boolean comprovarSelectorCurso()
    {
        return !comboBoxCursos.getSelectedItem().equals("Seleccionar curso");
    }
    
    private String extraerNombreComboBoxSelectedItem()
    {
        return comboBoxCursos.getSelectedItem().toString().substring(comboBoxCursos.getSelectedItem().toString().indexOf(":")+2, comboBoxCursos.getSelectedItem().toString().indexOf(","));
    }
    
    private void txtSelectorArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelectorArchivoActionPerformed
        interpreteArchivo = new Interpreter();
        listaContenido = interpreteArchivo.importarArchivo(seleccionarArchivo());
        if(listaContenido != null)
        {
            actualizarTablaLista();
        }
        else{JOptionPane.showMessageDialog(this, "Error \n No se pudo importar el archivo.", "Mensaje Error", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_txtSelectorArchivoActionPerformed

    private boolean comprobarArchivo(String nombreArchivo)
    {
        return nombreArchivo.substring(nombreArchivo.indexOf("."), nombreArchivo.length()).equals(".csv");
    }
    
    private Object[][] comprobarLista()
    {
        if(listaContenido.isEmpty())
        {
            return new Object[0][0];
        }
        else
        {
            return interpreteArchivo.getConteridoTabla(listaContenido);
        }
    }
    
    private void actualizarTablaLista()
    {
       tablaLista.setModel(new javax.swing.table.DefaultTableModel(
            comprobarLista(),
            new String [] {
                "Num.","Nombre Completo", "Estado asistencia", "Hora entrada", "Minutos totales"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class,java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
                
            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            
            boolean[] canEdit = new boolean [] {false, false, false, false, false};

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        }); 
            tablaLista.getColumnModel().getColumn(0).setResizable(false);
            tablaLista.getColumnModel().getColumn(1).setResizable(false);
            tablaLista.getColumnModel().getColumn(2).setResizable(false);
            tablaLista.getColumnModel().getColumn(3).setResizable(false);
            tablaLista.getColumnModel().getColumn(4).setResizable(false);
            tablaLista.getColumnModel().getColumn(0).setPreferredWidth(1);
            tablaLista.getColumnModel().getColumn(1).setPreferredWidth(300);
    }
    
    
    private File seleccionarArchivo()
    {
        JFileChooser selectorArchivos = new JFileChooser();
        
        selectorArchivos.setFileFilter(new FileNameExtensionFilter(".csv", "csv"));
        
        int opcion = selectorArchivos.showOpenDialog(this);
        
        if(opcion ==JFileChooser.APPROVE_OPTION)
        {
            File archivo = selectorArchivos.getSelectedFile();
            return archivo;
        }
        else{return null;}
    }
    
    private void llenarComboBoxCursos()
    {
       List<Document> listaCursos = cursosRepo.buscarRegistrosEnLaColeccion();
       for(int cont=0 ;cont < listaCursos.size() ;cont++)
       {
           comboBoxCursos.addItem("Nombre: "+listaCursos.get(cont).getString("nombre")+
                                ", Periodo: "+listaCursos.get(cont).getString("periodo")+
                                ", Dias: "+listaCursos.get(cont).getString("dias")+
                                ", Hora: "+listaCursos.get(cont).getString("hora"));
       }
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonBuscarArchivo;
    private javax.swing.JButton botonCanelar;
    private javax.swing.JComboBox<String> comboBoxCursos;
    private javax.swing.JLabel etiquetaSeleccionarArchivo;
    private javax.swing.JLabel etiquetaSeleccionarCurso;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JScrollPane scrollPanelTablaLista;
    private javax.swing.JTable tablaLista;
    private javax.swing.JTextField txtSelectorArchivo;
    // End of variables declaration//GEN-END:variables

    
   
}
