/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;

import java.util.ArrayList;
import org.bson.Document;
import repository.CursosRepository;

/**
 *
 * @author Alfredo Perez
 */
public class DlgMostrarCursos extends javax.swing.JDialog 
{
    private CursosRepository cursosRepo;
    
    /**
     * Creates new form DlgMostrarCursos
     * @param parent
     * @param modal
     * @param cursosRepo
     */
    public DlgMostrarCursos(java.awt.Frame parent, boolean modal, CursosRepository cursosRepo) 
    {
        super(parent, modal);
        this.initComponents();
        this.cursosRepo = cursosRepo;
        this.actualizarTablaCursos();
        this.setTitle("Mostrar Cursos");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        ScrollPanelTabla = new javax.swing.JScrollPane();
        tablaCursos = new javax.swing.JTable();
        etiquetaTitulo = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(240, 202, 171));
        panelFondo.setPreferredSize(new java.awt.Dimension(800, 500));

        tablaCursos.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ScrollPanelTabla.setViewportView(tablaCursos);

        etiquetaTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        etiquetaTitulo.setText("Lista de cursos registrados");

        botonSalir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPanelTabla)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(etiquetaTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                        .addGap(0, 697, Short.MAX_VALUE)
                        .addComponent(botonSalir)))
                .addGap(25, 25, 25))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(etiquetaTitulo)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(ScrollPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSalir)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void actualizarTablaCursos()
    {
        ArrayList<Document> cursos = this.cursosRepo.buscarRegistrosEnLaColeccion();
        
        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
                setObjetosTablaCursos(cursos),
            new String [] {"Nombre Curso", "Periodo", "Dias", "Hora"}
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
                
            @Override
            public Class getColumnClass(int columnIndex) {return types [columnIndex];}
            
            boolean[] canEdit = new boolean [] {false, false, false, false};

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {return canEdit [columnIndex];}
        }); 
       
        if (tablaCursos.getColumnModel().getColumnCount() < 8) 
        {
            tablaCursos.getColumnModel().getColumn(0).setResizable(false);
            tablaCursos.getColumnModel().getColumn(1).setResizable(false);
            tablaCursos.getColumnModel().getColumn(2).setResizable(false);
            tablaCursos.getColumnModel().getColumn(3).setResizable(false);
        }
        
    }
    
    private Object[][] setObjetosTablaCursos(ArrayList<Document> cursos)
    {
        Object[][] cursosTabla = new Object[cursos.size()][4];
        for(int cont=0; cont < cursos.size() ;cont++)
        {
            cursosTabla[cont][0] = cursos.get(cont).getString("nombre");
            cursosTabla[cont][1] = cursos.get(cont).getString("periodo");
            cursosTabla[cont][2] = cursos.get(cont).getString("dias");
            cursosTabla[cont][3] = cursos.get(cont).getString("hora");
        }
        return cursosTabla;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPanelTabla;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTable tablaCursos;
    // End of variables declaration//GEN-END:variables
}
