/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.bson.Document;
import repository.AsistenciaCursosRepository;
import repository.CursosRepository;
import repository.UnidadesRepository;

/**
 *
 * @author Alfredo Perez
 */
public class DlgMostrarCursos extends javax.swing.JDialog 
{
    private CursosRepository cursosRepo;
    private ArrayList<Document> listaCursos;
    private AsistenciaCursosRepository asistenciaCursosRepository;
    private UnidadesRepository unidadesRepository;
    /**
     * Creates new form DlgMostrarCursos
     * @param parent
     * @param modal
     * @param cursosRepo
     * @param accion
     */
    public DlgMostrarCursos(java.awt.Frame parent, boolean modal, CursosRepository cursosRepo,int accion) 
    {
        super(parent, modal);
        this.initComponents();
        this.cursosRepo = cursosRepo;
        this.listaCursos = new ArrayList<>();
        this.actualizarTablaCursos();
        this.setTitle("Mostrar Cursos");
        this.setVisible(true);
    }

    
    /**
     * Creates new form DlgMostrarCursos
     * @param parent
     * @param modal
     * @param cursosRepo
     * @param asistenciaCursosRepository
     * @param unidadesRepository
     * @param accion
     */
    public DlgMostrarCursos(java.awt.Frame parent, boolean modal, CursosRepository cursosRepo,AsistenciaCursosRepository asistenciaCursosRepository, UnidadesRepository unidadesRepository, int accion) 
    {
        super(parent, modal);
        this.initComponents();
        this.cursosRepo = cursosRepo;
        this.unidadesRepository = unidadesRepository;
        this.asistenciaCursosRepository = asistenciaCursosRepository;
        this.listaCursos = new ArrayList<>();
        this.actualizarTablaCursos();
        this.configurarParaModificar();
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        ScrollPanelTabla = new javax.swing.JScrollPane();
        tablaCursos = new javax.swing.JTable();
        etiquetaTitulo = new javax.swing.JLabel();
        panelBotonSalir = new javax.swing.JPanel();
        botonSalir7 = new javax.swing.JButton();
        panelBotonEliminar = new javax.swing.JPanel();
        botonEliminar = new javax.swing.JButton();
        panelBotonModificar = new javax.swing.JPanel();
        botonModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(240, 202, 171));
        panelFondo.setPreferredSize(new java.awt.Dimension(800, 500));
        panelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelFondoMousePressed(evt);
            }
        });

        tablaCursos.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaCursos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaCursosMousePressed(evt);
            }
        });
        ScrollPanelTabla.setViewportView(tablaCursos);

        etiquetaTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        etiquetaTitulo.setText("Lista de cursos registrados");

        panelBotonSalir.setBackground(new java.awt.Color(0, 0, 0));
        panelBotonSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotonSalir.setPreferredSize(new java.awt.Dimension(80, 30));

        botonSalir7.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        botonSalir7.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir7.setText("Salir");
        botonSalir7.setContentAreaFilled(false);
        botonSalir7.setPreferredSize(new java.awt.Dimension(80, 30));
        botonSalir7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonSalirLayout = new javax.swing.GroupLayout(panelBotonSalir);
        panelBotonSalir.setLayout(panelBotonSalirLayout);
        panelBotonSalirLayout.setHorizontalGroup(
            panelBotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonSalirLayout.createSequentialGroup()
                .addComponent(botonSalir7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelBotonSalirLayout.setVerticalGroup(
            panelBotonSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonSalir7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelBotonEliminar.setBackground(new java.awt.Color(102, 102, 102));
        panelBotonEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotonEliminar.setPreferredSize(new java.awt.Dimension(90, 30));
        panelBotonEliminar.setVisible(false);

        botonEliminar.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminar.setText("Eliminar");
        botonEliminar.setContentAreaFilled(false);
        botonEliminar.setEnabled(false);
        botonEliminar.setPreferredSize(new java.awt.Dimension(90, 30));
        botonEliminar.setVisible(false);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonEliminarLayout = new javax.swing.GroupLayout(panelBotonEliminar);
        panelBotonEliminar.setLayout(panelBotonEliminarLayout);
        panelBotonEliminarLayout.setHorizontalGroup(
            panelBotonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonEliminarLayout.createSequentialGroup()
                .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelBotonEliminarLayout.setVerticalGroup(
            panelBotonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonEliminarLayout.createSequentialGroup()
                .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelBotonModificar.setBackground(new java.awt.Color(102, 102, 102));
        panelBotonModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotonModificar.setPreferredSize(new java.awt.Dimension(90, 30));
        panelBotonModificar.setVisible(false);

        botonModificar.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        botonModificar.setForeground(new java.awt.Color(255, 255, 255));
        botonModificar.setText("Modificar");
        botonModificar.setContentAreaFilled(false);
        botonModificar.setEnabled(false);
        botonModificar.setPreferredSize(new java.awt.Dimension(90, 30));
        botonModificar.setVisible(false);
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonModificarLayout = new javax.swing.GroupLayout(panelBotonModificar);
        panelBotonModificar.setLayout(panelBotonModificarLayout);
        panelBotonModificarLayout.setHorizontalGroup(
            panelBotonModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonModificarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBotonModificarLayout.setVerticalGroup(
            panelBotonModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonModificarLayout.createSequentialGroup()
                .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(panelBotonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(panelBotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelBotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ScrollPanelTabla)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(etiquetaTitulo)
                        .addGap(0, 294, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(etiquetaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(ScrollPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBotonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     private void configurarParaModificar()
     {
        this.setTitle("Menu modificar cursos");
        this.panelBotonEliminar.setVisible(true);
        this.botonModificar.setVisible(true);
        this.panelBotonModificar.setVisible(true);
        this.botonEliminar.setVisible(true);
     }
     
    private void tablaCursosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCursosMousePressed
       if(tablaCursos.getSelectedRow() != -1)
       {
           panelBotonModificar.setBackground(new Color(51,255,51));
           botonModificar.setEnabled(true);
           panelBotonEliminar.setBackground(new Color(255,0,0));
           botonEliminar.setEnabled(true);
       }
    }//GEN-LAST:event_tablaCursosMousePressed

    private void panelFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFondoMousePressed
           panelBotonModificar.setBackground(new Color(102,102,102));
           botonModificar.setEnabled(false);
           panelBotonEliminar.setBackground(new Color(102,102,102));
           botonEliminar.setEnabled(false);
           tablaCursos.clearSelection();
    }//GEN-LAST:event_panelFondoMousePressed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
       DlgAgregarCurso modificarCurso = new DlgAgregarCurso(null, rootPaneCheckingEnabled, cursosRepo, asistenciaCursosRepository, unidadesRepository ,listaCursos.get(tablaCursos.getSelectedRow()));
       actualizarTablaCursos();
           panelBotonModificar.setBackground(new Color(102,102,102));
           botonModificar.setEnabled(false);
           panelBotonEliminar.setBackground(new Color(102,102,102));
           botonEliminar.setEnabled(false);
           tablaCursos.clearSelection();
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
       Document curso = listaCursos.get(tablaCursos.getSelectedRow());
       int respuesta = JOptionPane.showConfirmDialog(this, "Si elimina el curso con el "+"Nombre: "+curso.getString("nombre")+", Periodo: "+curso.getString("periodo")+", Dias: "+curso.getString("dias")+", Hora: "+curso.getString("hora")+
       "\n ademas del curso se eliminaran las unidades de competencias y las asistencias registradas en el curso\n ¿Esta seguro de eliminar el curso?", "Mensaje Confirmacion", JOptionPane.YES_NO_OPTION);
       if(respuesta == 0)
       {
           cursosRepo.eliminarCurso(curso);
           unidadesRepository.eliminarUnidadesEnElCurso(curso);
           asistenciaCursosRepository.eliminarAsistenciasEnElCurso(curso);
           actualizarTablaCursos();
           JOptionPane.showMessageDialog(this, "El curso se elimino correctamente", "Mensaje Aviso", JOptionPane.INFORMATION_MESSAGE);
       }
           panelBotonModificar.setBackground(new Color(102,102,102));
           botonModificar.setEnabled(false);
           panelBotonEliminar.setBackground(new Color(102,102,102));
           botonEliminar.setEnabled(false);
           tablaCursos.clearSelection();
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void actualizarTablaCursos()
    {
        listaCursos = this.cursosRepo.buscarRegistrosEnLaColeccion();
        
        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
                setObjetosTablaCursos(listaCursos),
            new String [] {"Nombre Curso", "Periodo", "Dias", "Hora"}
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
                
            @Override
            public Class getColumnClass(int columnIndex) {return types [columnIndex];}
            
            boolean[] canEdit = new boolean [] {false, false, false, false};

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {return canEdit [columnIndex];}
        }); 
       
        if (tablaCursos.getColumnModel().getColumnCount() < 8) 
        {
            tablaCursos.getColumnModel().getColumn(0).setResizable(false);
            tablaCursos.getColumnModel().getColumn(1).setResizable(false);
            tablaCursos.getColumnModel().getColumn(2).setResizable(false);
            tablaCursos.getColumnModel().getColumn(3).setResizable(false);
        }
        
    }
    
    private Object[][] setObjetosTablaCursos(ArrayList<Document> cursos)
    {
        Object[][] cursosTabla = new Object[cursos.size()][4];
        for(int cont=0; cont < cursos.size() ;cont++)
        {
            cursosTabla[cont][0] = cursos.get(cont).getString("nombre");
            cursosTabla[cont][1] = cursos.get(cont).getString("periodo");
            cursosTabla[cont][2] = cursos.get(cont).getString("dias");
            cursosTabla[cont][3] = cursos.get(cont).getString("hora");
        }
        return cursosTabla;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPanelTabla;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonSalir1;
    private javax.swing.JButton botonSalir2;
    private javax.swing.JButton botonSalir3;
    private javax.swing.JButton botonSalir4;
    private javax.swing.JButton botonSalir5;
    private javax.swing.JButton botonSalir6;
    private javax.swing.JButton botonSalir7;
    private javax.swing.JPanel cajaSalir;
    private javax.swing.JPanel cajaSalir1;
    private javax.swing.JPanel cajaSalir2;
    private javax.swing.JPanel cajaSalir3;
    private javax.swing.JPanel cajaSalir4;
    private javax.swing.JPanel cajaSalir5;
    private javax.swing.JPanel cajaSalir6;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel panelBotonEliminar;
    private javax.swing.JPanel panelBotonModificar;
    private javax.swing.JPanel panelBotonSalir;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTable tablaCursos;
    // End of variables declaration//GEN-END:variables
}
