/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import org.bson.Document;
import repository.CursosRepository;
import repository.UnidadesRepository;

/**
 *
 * @author Alfredo Perez
 */
public class DlgMostrarUnidades extends javax.swing.JDialog 
{

    private UnidadesRepository unidadesRepoitory;
    private CursosRepository cursosRepo;
    private List<Document> listaUnidades;
    
    
    /**
     * Creates new form DlgMostrarUnidades
     * @param parent
     * @param modal
     * @param cursosRepo
     * @param unidadesRepoitory
     */
    public DlgMostrarUnidades(java.awt.Frame parent, boolean modal, CursosRepository cursosRepo, UnidadesRepository unidadesRepoitory)
    {
        super(parent, modal);
        this.initComponents();
        this.cursosRepo = cursosRepo;
        this.unidadesRepoitory = unidadesRepoitory;
        this.llenarComboBoxCursos();
        this.actualizarTablaCursos();
        this.setTitle("Mostrar Unidades");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        etiquetaTitulo = new javax.swing.JLabel();
        ScrollPanelTabla = new javax.swing.JScrollPane();
        tablaUnidades = new javax.swing.JTable();
        botonSalir = new javax.swing.JButton();
        comboSeleccionarCurso = new javax.swing.JComboBox<>();
        etiquetaSeleccionarCurso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(808, 580));
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(240, 202, 171));
        panelFondo.setPreferredSize(new java.awt.Dimension(800, 580));

        etiquetaTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        etiquetaTitulo.setText("Lista de unidades registradas");

        tablaUnidades.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tablaUnidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ScrollPanelTabla.setViewportView(tablaUnidades);

        botonSalir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        comboSeleccionarCurso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboSeleccionarCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un curso" }));
        comboSeleccionarCurso.setPreferredSize(new java.awt.Dimension(290, 29));
        comboSeleccionarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionarCursoActionPerformed(evt);
            }
        });

        etiquetaSeleccionarCurso.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        etiquetaSeleccionarCurso.setText("Seleccionar curso: ");

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScrollPanelTabla)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(etiquetaTitulo)
                                .addGap(0, 247, Short.MAX_VALUE))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(etiquetaSeleccionarCurso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboSeleccionarCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(25, 25, 25))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(etiquetaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaSeleccionarCurso)
                    .addComponent(comboSeleccionarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(ScrollPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSalir)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboSeleccionarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionarCursoActionPerformed
       if(comboSeleccionarCurso.getSelectedIndex()!=0)
       {
           listaUnidades = unidadesRepoitory.buscarUnidades(extraerCurso());
           if(listaUnidades != null){actualizarTablaCursos();}
           else{JOptionPane.showMessageDialog(null, "Error \n No se encontro ninguna unidad \n registrada en este curso!", "Mensaje Error", JOptionPane.ERROR_MESSAGE);}
       }
       else
       {
          listaUnidades = new ArrayList<>();
          actualizarTablaCursos();
       }
    }//GEN-LAST:event_comboSeleccionarCursoActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private Document extraerCurso()
    {
        String[] curso;
        Document documentoCurso = new Document();
        curso = comboSeleccionarCurso.getSelectedItem().toString().split(",");
        documentoCurso.append("nombre", curso[0].substring(curso[0].indexOf(":")+2, curso[0].length()));
        documentoCurso.append("periodo", curso[1].substring(curso[1].indexOf(":")+2, curso[1].length()));
        documentoCurso.append("dias", curso[2].substring(curso[2].indexOf(":")+2, curso[2].length()));
        documentoCurso.append("hora", curso[3].substring(curso[3].indexOf(":")+2, curso[3].length()));
        return documentoCurso;
    }
    
    private void llenarComboBoxCursos()
    {
       List<Document> listaCursos = cursosRepo.buscarRegistrosEnLaColeccion();
       for(int cont=0 ;cont < listaCursos.size() ;cont++)
       {
           comboSeleccionarCurso.addItem("Nombre: "+listaCursos.get(cont).getString("nombre")+
                                       ", Periodo: "+listaCursos.get(cont).getString("periodo")+
                                       ", Dias: "+listaCursos.get(cont).getString("dias")+
                                       ", Hora: "+listaCursos.get(cont).getString("hora"));
       }
    }
    
    private void actualizarTablaCursos()
    {
        tablaUnidades.setModel(new javax.swing.table.DefaultTableModel(
                setObjetosTablaUnidades(listaUnidades),
            new String [] {"Indice", "Nombre Unidad", "Descripcion"}
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
                
            @Override
            public Class getColumnClass(int columnIndex) {return types [columnIndex];}
            
            boolean[] canEdit = new boolean [] {false, false, false};

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {return canEdit [columnIndex];}
        }); 
       
        if (tablaUnidades.getColumnModel().getColumnCount() < 8) 
        {
            TableColumnModel columnModel = tablaUnidades.getColumnModel();
            tablaUnidades.getColumnModel().getColumn(0).setResizable(false);
            tablaUnidades.getColumnModel().getColumn(1).setResizable(false);
            tablaUnidades.getColumnModel().getColumn(2).setResizable(false);
            columnModel.getColumn(0).setPreferredWidth(10);
            columnModel.getColumn(1).setPreferredWidth(250);
            columnModel.getColumn(2).setPreferredWidth(350);
            tablaUnidades.setColumnModel(columnModel);
        }
        
    }
    
    private Object[][] setObjetosTablaUnidades(List<Document> unidades)
    {
      if(unidades != null)
      {  
        Object[][] unidadesTabla = new Object[unidades.size()][3];
        for(int cont=0; cont < unidades.size() ;cont++)
        {
            int indice = Integer.valueOf(unidades.get(cont).getString("indice"));
            int pos=0;
            for(int cont2=0 ; cont2 < unidades.size() ;cont2++)
            {
                int indice2 = Integer.valueOf(unidades.get(cont2).getString("indice"));
                if(indice != indice2)
                {
                    if(indice > indice2)
                    {
                        pos = pos+1;
                    }
                }
            }
            unidadesTabla[pos][0] = unidades.get(cont).getString("indice");
            unidadesTabla[pos][1] = unidades.get(cont).getString("nombre");
            unidadesTabla[pos][2] = unidades.get(cont).getString("descripcion");
        }
        return unidadesTabla;
      }
      else
      {
          return new Object[0][0];
      }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPanelTabla;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> comboSeleccionarCurso;
    private javax.swing.JLabel etiquetaSeleccionarCurso;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTable tablaUnidades;
    // End of variables declaration//GEN-END:variables
}
