package interfazUsuario;

import repository.*;

/**
 *
 * @author PC
 */
public class JFrameMenuPrincipal extends javax.swing.JFrame {
    
    private static CursosRepository cursosRepo;
    private static AsistenciaCursosRepository asistenciaCursosRepository;

    /**
     * Creates new form MenuPrincipal
     */
    public JFrameMenuPrincipal() 
    {
        cursosRepo = new CursosRepository();
        asistenciaCursosRepository = new AsistenciaCursosRepository();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        cajaAgregarCurso = new javax.swing.JPanel();
        botonAgregarCurso = new javax.swing.JButton();
        etiquetaAgragarCursos = new javax.swing.JLabel();
        etiquetaTitulo = new javax.swing.JLabel();
        cajaMostrarCurso = new javax.swing.JPanel();
        botonMostrarCurso = new javax.swing.JButton();
        etiquetaMostrarCurso = new javax.swing.JLabel();
        cajaAgregarAsistencia = new javax.swing.JPanel();
        etiquetaAgregarAsistencia = new javax.swing.JLabel();
        botonAgregarAsistencia = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(240, 202, 171));
        panelFondo.setBorder(new javax.swing.border.MatteBorder(null));
        panelFondo.setPreferredSize(new java.awt.Dimension(605, 605));

        cajaAgregarCurso.setBackground(new java.awt.Color(202, 7, 54));
        cajaAgregarCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonAgregarCurso.setBackground(new java.awt.Color(202, 7, 54));
        botonAgregarCurso.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonAgregarCurso.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregarCurso.setText("Agregar Curso");
        botonAgregarCurso.setToolTipText("");
        botonAgregarCurso.setBorder(null);
        botonAgregarCurso.setBorderPainted(false);
        botonAgregarCurso.setContentAreaFilled(false);
        botonAgregarCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAgregarCurso.setFocusPainted(false);
        botonAgregarCurso.setMargin(null);
        botonAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarCursoActionPerformed(evt);
            }
        });

        etiquetaAgragarCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cursos-iconoNaranja.png"))); // NOI18N
        etiquetaAgragarCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout cajaAgregarCursoLayout = new javax.swing.GroupLayout(cajaAgregarCurso);
        cajaAgregarCurso.setLayout(cajaAgregarCursoLayout);
        cajaAgregarCursoLayout.setHorizontalGroup(
            cajaAgregarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cajaAgregarCursoLayout.createSequentialGroup()
                .addComponent(etiquetaAgragarCursos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cajaAgregarCursoLayout.setVerticalGroup(
            cajaAgregarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaAgregarCursoLayout.createSequentialGroup()
                .addGroup(cajaAgregarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaAgragarCursos))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        etiquetaTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        etiquetaTitulo.setText("Administrador de cursos");

        cajaMostrarCurso.setBackground(new java.awt.Color(112, 141, 123));
        cajaMostrarCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaMostrarCurso.setPreferredSize(new java.awt.Dimension(326, 82));

        botonMostrarCurso.setBackground(new java.awt.Color(112, 253, 110));
        botonMostrarCurso.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonMostrarCurso.setForeground(new java.awt.Color(255, 255, 255));
        botonMostrarCurso.setText("Mostrar Cursos");
        botonMostrarCurso.setBorderPainted(false);
        botonMostrarCurso.setContentAreaFilled(false);
        botonMostrarCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMostrarCurso.setFocusPainted(false);
        botonMostrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarCursoActionPerformed(evt);
            }
        });

        etiquetaMostrarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mostrarCursos-icono.png"))); // NOI18N

        javax.swing.GroupLayout cajaMostrarCursoLayout = new javax.swing.GroupLayout(cajaMostrarCurso);
        cajaMostrarCurso.setLayout(cajaMostrarCursoLayout);
        cajaMostrarCursoLayout.setHorizontalGroup(
            cajaMostrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cajaMostrarCursoLayout.createSequentialGroup()
                .addComponent(etiquetaMostrarCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMostrarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cajaMostrarCursoLayout.setVerticalGroup(
            cajaMostrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cajaMostrarCursoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(cajaMostrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonMostrarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaMostrarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        cajaAgregarAsistencia.setBackground(new java.awt.Color(103, 155, 255));
        cajaAgregarAsistencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaAgregarAsistencia.setPreferredSize(new java.awt.Dimension(326, 82));

        etiquetaAgregarAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asistencia-icono.png"))); // NOI18N

        botonAgregarAsistencia.setBackground(new java.awt.Color(103, 155, 255));
        botonAgregarAsistencia.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        botonAgregarAsistencia.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregarAsistencia.setText("Agregar Asistencia");
        botonAgregarAsistencia.setBorderPainted(false);
        botonAgregarAsistencia.setContentAreaFilled(false);
        botonAgregarAsistencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAgregarAsistencia.setFocusPainted(false);
        botonAgregarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarAsistenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cajaAgregarAsistenciaLayout = new javax.swing.GroupLayout(cajaAgregarAsistencia);
        cajaAgregarAsistencia.setLayout(cajaAgregarAsistenciaLayout);
        cajaAgregarAsistenciaLayout.setHorizontalGroup(
            cajaAgregarAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaAgregarAsistenciaLayout.createSequentialGroup()
                .addComponent(etiquetaAgregarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAgregarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        cajaAgregarAsistenciaLayout.setVerticalGroup(
            cajaAgregarAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaAgregarAsistenciaLayout.createSequentialGroup()
                .addGroup(cajaAgregarAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaAgregarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(cajaAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(cajaMostrarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaTitulo)
                            .addComponent(cajaAgregarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(333, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(etiquetaTitulo)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajaAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaMostrarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(cajaAgregarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jButton1)
                .addGap(229, 229, 229))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelFondo.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarCursoActionPerformed
        //setVisible(false);
        DlgAgregarCurso agregarCurso = new DlgAgregarCurso(this, rootPaneCheckingEnabled, cursosRepo);
    }//GEN-LAST:event_botonAgregarCursoActionPerformed

    private void botonMostrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarCursoActionPerformed
        //setVisible(false);
        DlgMostrarCursos mostrarCursos = new DlgMostrarCursos(this, rootPaneCheckingEnabled, cursosRepo);
    }//GEN-LAST:event_botonMostrarCursoActionPerformed

    private void botonAgregarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarAsistenciaActionPerformed
        //setVisible(false);
        DlgAgregarAsistencia agregarAsistencia = new DlgAgregarAsistencia(this, rootPaneCheckingEnabled, asistenciaCursosRepository, cursosRepo);
    }//GEN-LAST:event_botonAgregarAsistenciaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarAsistencia;
    private javax.swing.JButton botonAgregarCurso;
    private javax.swing.JButton botonMostrarCurso;
    private javax.swing.JPanel cajaAgregarAsistencia;
    private javax.swing.JPanel cajaAgregarCurso;
    private javax.swing.JPanel cajaMostrarCurso;
    private javax.swing.JLabel etiquetaAgragarCursos;
    private javax.swing.JLabel etiquetaAgregarAsistencia;
    private javax.swing.JLabel etiquetaMostrarCurso;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables
}
