package interfazUsuario;

import repository.*;

/**
 *
 * @author PC
 */
public class JFrameMenuPrincipal extends javax.swing.JFrame {
    
    private static CursosRepository cursosRepo;
    private static AsistenciaCursosRepository asistenciaCursosRepository;
    private static UnidadesRepository unidadesRepository;

    /**
     * Creates new form MenuPrincipal
     */
    public JFrameMenuPrincipal() 
    {
        cursosRepo = new CursosRepository();
        unidadesRepository = new UnidadesRepository();
        asistenciaCursosRepository = new AsistenciaCursosRepository();
        initComponents();
        this.setTitle("Principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        etiquetaTitulo = new javax.swing.JLabel();
        cajaAgregarCurso = new javax.swing.JPanel();
        botonAgregarCurso = new javax.swing.JButton();
        etiquetaAgragarCursos = new javax.swing.JLabel();
        cajaMostrarCurso = new javax.swing.JPanel();
        botonMostrarCurso = new javax.swing.JButton();
        etiquetaMostrarCurso = new javax.swing.JLabel();
        cajaAgregarUnidad = new javax.swing.JPanel();
        etiquetaAgregarUnidad = new javax.swing.JLabel();
        botonAgregarUnidad = new javax.swing.JButton();
        cajaMostrarUnidades = new javax.swing.JPanel();
        etiquetaMostrarUnidades = new javax.swing.JLabel();
        botonMostrarUnidades = new javax.swing.JButton();
        cajaAgregarAsistencia = new javax.swing.JPanel();
        etiquetaAgregarAsistencia = new javax.swing.JLabel();
        botonAgregarAsistencia = new javax.swing.JButton();
        cajaMostrarListaAsistencias = new javax.swing.JPanel();
        etiquetaMostrarListasAsistencias = new javax.swing.JLabel();
        botonMostrarListasAsistencias = new javax.swing.JButton();
        cajaModificarAsistencias = new javax.swing.JPanel();
        etiquetaModificarAsistencias = new javax.swing.JLabel();
        botonModificarAsistencias = new javax.swing.JButton();
        cajaSalir = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(240, 202, 171));
        panelFondo.setPreferredSize(new java.awt.Dimension(800, 486));

        etiquetaTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        etiquetaTitulo.setText("Administrador de cursos");

        cajaAgregarCurso.setBackground(new java.awt.Color(202, 7, 54));
        cajaAgregarCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonAgregarCurso.setBackground(new java.awt.Color(202, 7, 54));
        botonAgregarCurso.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonAgregarCurso.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregarCurso.setText("Agregar Curso");
        botonAgregarCurso.setToolTipText("");
        botonAgregarCurso.setBorder(null);
        botonAgregarCurso.setBorderPainted(false);
        botonAgregarCurso.setContentAreaFilled(false);
        botonAgregarCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAgregarCurso.setFocusPainted(false);
        botonAgregarCurso.setMargin(null);
        botonAgregarCurso.setPreferredSize(new java.awt.Dimension(240, 80));
        botonAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarCursoActionPerformed(evt);
            }
        });

        etiquetaAgragarCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cursos-iconoNaranja.png"))); // NOI18N
        etiquetaAgragarCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        etiquetaAgragarCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                etiquetaAgragarCursosMousePressed(evt);
            }
        });

        javax.swing.GroupLayout cajaAgregarCursoLayout = new javax.swing.GroupLayout(cajaAgregarCurso);
        cajaAgregarCurso.setLayout(cajaAgregarCursoLayout);
        cajaAgregarCursoLayout.setHorizontalGroup(
            cajaAgregarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cajaAgregarCursoLayout.createSequentialGroup()
                .addComponent(etiquetaAgragarCursos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cajaAgregarCursoLayout.setVerticalGroup(
            cajaAgregarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaAgregarCursoLayout.createSequentialGroup()
                .addGroup(cajaAgregarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaAgragarCursos))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cajaMostrarCurso.setBackground(new java.awt.Color(112, 141, 123));
        cajaMostrarCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaMostrarCurso.setPreferredSize(new java.awt.Dimension(326, 82));

        botonMostrarCurso.setBackground(new java.awt.Color(112, 253, 110));
        botonMostrarCurso.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonMostrarCurso.setForeground(new java.awt.Color(255, 255, 255));
        botonMostrarCurso.setText("Mostrar Cursos");
        botonMostrarCurso.setBorderPainted(false);
        botonMostrarCurso.setContentAreaFilled(false);
        botonMostrarCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMostrarCurso.setFocusPainted(false);
        botonMostrarCurso.setPreferredSize(new java.awt.Dimension(240, 80));
        botonMostrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarCursoActionPerformed(evt);
            }
        });

        etiquetaMostrarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mostrarCursos-icono.png"))); // NOI18N
        etiquetaMostrarCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                etiquetaMostrarCursoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout cajaMostrarCursoLayout = new javax.swing.GroupLayout(cajaMostrarCurso);
        cajaMostrarCurso.setLayout(cajaMostrarCursoLayout);
        cajaMostrarCursoLayout.setHorizontalGroup(
            cajaMostrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cajaMostrarCursoLayout.createSequentialGroup()
                .addComponent(etiquetaMostrarCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMostrarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cajaMostrarCursoLayout.setVerticalGroup(
            cajaMostrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cajaMostrarCursoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(cajaMostrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonMostrarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaMostrarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        cajaAgregarUnidad.setBackground(new java.awt.Color(0, 51, 51));
        cajaAgregarUnidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaAgregarUnidad.setPreferredSize(new java.awt.Dimension(326, 82));

        etiquetaAgregarUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregarUnidad_icono.png"))); // NOI18N
        etiquetaAgregarUnidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                etiquetaAgregarUnidadMousePressed(evt);
            }
        });

        botonAgregarUnidad.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonAgregarUnidad.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregarUnidad.setText("Agregar Unidad");
        botonAgregarUnidad.setContentAreaFilled(false);
        botonAgregarUnidad.setPreferredSize(new java.awt.Dimension(240, 80));
        botonAgregarUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarUnidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cajaAgregarUnidadLayout = new javax.swing.GroupLayout(cajaAgregarUnidad);
        cajaAgregarUnidad.setLayout(cajaAgregarUnidadLayout);
        cajaAgregarUnidadLayout.setHorizontalGroup(
            cajaAgregarUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaAgregarUnidadLayout.createSequentialGroup()
                .addComponent(etiquetaAgregarUnidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAgregarUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cajaAgregarUnidadLayout.setVerticalGroup(
            cajaAgregarUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cajaAgregarUnidadLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(etiquetaAgregarUnidad))
            .addGroup(cajaAgregarUnidadLayout.createSequentialGroup()
                .addComponent(botonAgregarUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cajaMostrarUnidades.setBackground(new java.awt.Color(209, 216, 20));
        cajaMostrarUnidades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaMostrarUnidades.setPreferredSize(new java.awt.Dimension(326, 82));

        etiquetaMostrarUnidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mostrarUnidades_icono.png"))); // NOI18N
        etiquetaMostrarUnidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                etiquetaMostrarUnidadesMousePressed(evt);
            }
        });

        botonMostrarUnidades.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        botonMostrarUnidades.setForeground(new java.awt.Color(255, 255, 255));
        botonMostrarUnidades.setText("Mostrar Unidades");
        botonMostrarUnidades.setContentAreaFilled(false);
        botonMostrarUnidades.setPreferredSize(new java.awt.Dimension(240, 80));
        botonMostrarUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarUnidadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cajaMostrarUnidadesLayout = new javax.swing.GroupLayout(cajaMostrarUnidades);
        cajaMostrarUnidades.setLayout(cajaMostrarUnidadesLayout);
        cajaMostrarUnidadesLayout.setHorizontalGroup(
            cajaMostrarUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaMostrarUnidadesLayout.createSequentialGroup()
                .addComponent(etiquetaMostrarUnidades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMostrarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cajaMostrarUnidadesLayout.setVerticalGroup(
            cajaMostrarUnidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cajaMostrarUnidadesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(etiquetaMostrarUnidades))
            .addComponent(botonMostrarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        cajaAgregarAsistencia.setBackground(new java.awt.Color(103, 155, 255));
        cajaAgregarAsistencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaAgregarAsistencia.setPreferredSize(new java.awt.Dimension(326, 82));

        etiquetaAgregarAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asistencia-icono.png"))); // NOI18N
        etiquetaAgregarAsistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                etiquetaAgregarAsistenciaMousePressed(evt);
            }
        });

        botonAgregarAsistencia.setBackground(new java.awt.Color(103, 155, 255));
        botonAgregarAsistencia.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        botonAgregarAsistencia.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregarAsistencia.setText("Agregar Asistencia");
        botonAgregarAsistencia.setBorderPainted(false);
        botonAgregarAsistencia.setContentAreaFilled(false);
        botonAgregarAsistencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAgregarAsistencia.setFocusPainted(false);
        botonAgregarAsistencia.setPreferredSize(new java.awt.Dimension(240, 80));
        botonAgregarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarAsistenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cajaAgregarAsistenciaLayout = new javax.swing.GroupLayout(cajaAgregarAsistencia);
        cajaAgregarAsistencia.setLayout(cajaAgregarAsistenciaLayout);
        cajaAgregarAsistenciaLayout.setHorizontalGroup(
            cajaAgregarAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaAgregarAsistenciaLayout.createSequentialGroup()
                .addComponent(etiquetaAgregarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAgregarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        cajaAgregarAsistenciaLayout.setVerticalGroup(
            cajaAgregarAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaAgregarAsistenciaLayout.createSequentialGroup()
                .addGroup(cajaAgregarAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaAgregarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cajaMostrarListaAsistencias.setBackground(new java.awt.Color(255, 108, 146));
        cajaMostrarListaAsistencias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaMostrarListaAsistencias.setPreferredSize(new java.awt.Dimension(326, 82));

        etiquetaMostrarListasAsistencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mostrarLista-icono.png"))); // NOI18N
        etiquetaMostrarListasAsistencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                etiquetaMostrarListasAsistenciasMousePressed(evt);
            }
        });

        botonMostrarListasAsistencias.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        botonMostrarListasAsistencias.setForeground(new java.awt.Color(255, 255, 255));
        botonMostrarListasAsistencias.setText("Mostrar Asistencias");
        botonMostrarListasAsistencias.setContentAreaFilled(false);
        botonMostrarListasAsistencias.setPreferredSize(new java.awt.Dimension(240, 80));
        botonMostrarListasAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarListasAsistenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cajaMostrarListaAsistenciasLayout = new javax.swing.GroupLayout(cajaMostrarListaAsistencias);
        cajaMostrarListaAsistencias.setLayout(cajaMostrarListaAsistenciasLayout);
        cajaMostrarListaAsistenciasLayout.setHorizontalGroup(
            cajaMostrarListaAsistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaMostrarListaAsistenciasLayout.createSequentialGroup()
                .addComponent(etiquetaMostrarListasAsistencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMostrarListasAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cajaMostrarListaAsistenciasLayout.setVerticalGroup(
            cajaMostrarListaAsistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaMostrarListaAsistenciasLayout.createSequentialGroup()
                .addGroup(cajaMostrarListaAsistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonMostrarListasAsistencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaMostrarListasAsistencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        cajaModificarAsistencias.setBackground(new java.awt.Color(102, 102, 102));
        cajaModificarAsistencias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaModificarAsistencias.setPreferredSize(new java.awt.Dimension(326, 82));

        etiquetaModificarAsistencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificarLista-icono2.png"))); // NOI18N
        etiquetaModificarAsistencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                etiquetaModificarAsistenciasMousePressed(evt);
            }
        });

        botonModificarAsistencias.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        botonModificarAsistencias.setForeground(new java.awt.Color(255, 255, 255));
        botonModificarAsistencias.setText("Modificar Asistencias");
        botonModificarAsistencias.setContentAreaFilled(false);
        botonModificarAsistencias.setPreferredSize(new java.awt.Dimension(240, 80));
        botonModificarAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarAsistenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cajaModificarAsistenciasLayout = new javax.swing.GroupLayout(cajaModificarAsistencias);
        cajaModificarAsistencias.setLayout(cajaModificarAsistenciasLayout);
        cajaModificarAsistenciasLayout.setHorizontalGroup(
            cajaModificarAsistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaModificarAsistenciasLayout.createSequentialGroup()
                .addComponent(etiquetaModificarAsistencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonModificarAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cajaModificarAsistenciasLayout.setVerticalGroup(
            cajaModificarAsistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajaModificarAsistenciasLayout.createSequentialGroup()
                .addGroup(cajaModificarAsistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiquetaModificarAsistencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonModificarAsistencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cajaSalir.setBackground(new java.awt.Color(0, 0, 0));

        botonSalir.setBackground(new java.awt.Color(255, 255, 153));
        botonSalir.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Salir");
        botonSalir.setContentAreaFilled(false);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cajaSalirLayout = new javax.swing.GroupLayout(cajaSalir);
        cajaSalir.setLayout(cajaSalirLayout);
        cajaSalirLayout.setHorizontalGroup(
            cajaSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cajaSalirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cajaSalirLayout.setVerticalGroup(
            cajaSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cajaSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cajaModificarAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaTitulo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(cajaAgregarUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cajaMostrarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cajaAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaAgregarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cajaMostrarCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaMostrarListaAsistencias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cajaSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(etiquetaTitulo)
                .addGap(27, 27, 27)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajaAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaMostrarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajaAgregarUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaMostrarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cajaAgregarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaMostrarListaAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(cajaModificarAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(cajaSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        panelFondo.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonModificarAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarAsistenciasActionPerformed
        DlgMostrarListasAsistencias modificarAsistencias = new DlgMostrarListasAsistencias(this, rootPaneCheckingEnabled, asistenciaCursosRepository, cursosRepo, ConstantesGUI.MODIFICAR);
    }//GEN-LAST:event_botonModificarAsistenciasActionPerformed

    private void etiquetaModificarAsistenciasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaModificarAsistenciasMousePressed
        DlgMostrarListasAsistencias modificarAsistencias = new DlgMostrarListasAsistencias(this, rootPaneCheckingEnabled, asistenciaCursosRepository, cursosRepo, ConstantesGUI.MODIFICAR);
    }//GEN-LAST:event_etiquetaModificarAsistenciasMousePressed

    private void botonMostrarListasAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarListasAsistenciasActionPerformed
        DlgModoMuestraListasAsistencias seleccionarModoMostrar = new DlgModoMuestraListasAsistencias(this, rootPaneCheckingEnabled, asistenciaCursosRepository, cursosRepo, unidadesRepository);
    }//GEN-LAST:event_botonMostrarListasAsistenciasActionPerformed

    private void etiquetaMostrarListasAsistenciasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaMostrarListasAsistenciasMousePressed
        DlgModoMuestraListasAsistencias seleccionarModoMostrar = new DlgModoMuestraListasAsistencias(this, rootPaneCheckingEnabled, asistenciaCursosRepository, cursosRepo, unidadesRepository);
    }//GEN-LAST:event_etiquetaMostrarListasAsistenciasMousePressed

    private void botonAgregarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarAsistenciaActionPerformed
        DlgAgregarAsistencia agregarAsistencia = new DlgAgregarAsistencia(this, rootPaneCheckingEnabled, asistenciaCursosRepository, cursosRepo, unidadesRepository);
    }//GEN-LAST:event_botonAgregarAsistenciaActionPerformed

    private void etiquetaAgregarAsistenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaAgregarAsistenciaMousePressed
        DlgAgregarAsistencia agregarAsistencia = new DlgAgregarAsistencia(this, rootPaneCheckingEnabled, asistenciaCursosRepository, cursosRepo, unidadesRepository);
    }//GEN-LAST:event_etiquetaAgregarAsistenciaMousePressed

    private void etiquetaMostrarCursoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaMostrarCursoMousePressed
        DlgMostrarCursos mostrarCursos = new DlgMostrarCursos(this, rootPaneCheckingEnabled, cursosRepo);
    }//GEN-LAST:event_etiquetaMostrarCursoMousePressed

    private void botonMostrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarCursoActionPerformed
        DlgMostrarCursos mostrarCursos = new DlgMostrarCursos(this, rootPaneCheckingEnabled, cursosRepo);
    }//GEN-LAST:event_botonMostrarCursoActionPerformed

    private void etiquetaAgragarCursosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaAgragarCursosMousePressed
        DlgAgregarCurso agregarCurso = new DlgAgregarCurso(this, rootPaneCheckingEnabled, cursosRepo);
    }//GEN-LAST:event_etiquetaAgragarCursosMousePressed

    private void botonAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarCursoActionPerformed
        DlgAgregarCurso agregarCurso = new DlgAgregarCurso(this, rootPaneCheckingEnabled, cursosRepo);
    }//GEN-LAST:event_botonAgregarCursoActionPerformed

    private void botonAgregarUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarUnidadActionPerformed
        DlgAgregarUnidad agregarUnidad = new DlgAgregarUnidad(this, rootPaneCheckingEnabled, cursosRepo, unidadesRepository);
    }//GEN-LAST:event_botonAgregarUnidadActionPerformed

    private void botonMostrarUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarUnidadesActionPerformed
        DlgMostrarUnidades mostrarUnidades = new DlgMostrarUnidades(this, rootPaneCheckingEnabled, cursosRepo, unidadesRepository);
    }//GEN-LAST:event_botonMostrarUnidadesActionPerformed

    private void etiquetaAgregarUnidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaAgregarUnidadMousePressed
        DlgAgregarUnidad agregarUnidad = new DlgAgregarUnidad(this, rootPaneCheckingEnabled, cursosRepo, unidadesRepository);
    }//GEN-LAST:event_etiquetaAgregarUnidadMousePressed

    private void etiquetaMostrarUnidadesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaMostrarUnidadesMousePressed
        DlgMostrarUnidades mostrarUnidades = new DlgMostrarUnidades(this, rootPaneCheckingEnabled, cursosRepo, unidadesRepository);
    }//GEN-LAST:event_etiquetaMostrarUnidadesMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarAsistencia;
    private javax.swing.JButton botonAgregarCurso;
    private javax.swing.JButton botonAgregarUnidad;
    private javax.swing.JButton botonModificarAsistencias;
    private javax.swing.JButton botonMostrarCurso;
    private javax.swing.JButton botonMostrarListasAsistencias;
    private javax.swing.JButton botonMostrarUnidades;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel cajaAgregarAsistencia;
    private javax.swing.JPanel cajaAgregarCurso;
    private javax.swing.JPanel cajaAgregarUnidad;
    private javax.swing.JPanel cajaModificarAsistencias;
    private javax.swing.JPanel cajaMostrarCurso;
    private javax.swing.JPanel cajaMostrarListaAsistencias;
    private javax.swing.JPanel cajaMostrarUnidades;
    private javax.swing.JPanel cajaSalir;
    private javax.swing.JLabel etiquetaAgragarCursos;
    private javax.swing.JLabel etiquetaAgregarAsistencia;
    private javax.swing.JLabel etiquetaAgregarUnidad;
    private javax.swing.JLabel etiquetaModificarAsistencias;
    private javax.swing.JLabel etiquetaMostrarCurso;
    private javax.swing.JLabel etiquetaMostrarListasAsistencias;
    private javax.swing.JLabel etiquetaMostrarUnidades;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables
}
